# Whole file generated by GPT

import subprocess
import time
import os
import sys

def interact_with_index(inputs):
    # Set the current working directory to the script's directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    process = subprocess.Popen(['python', 'index.py'], 
                               stdin=subprocess.PIPE, 
                               stdout=subprocess.PIPE, 
                               stderr=subprocess.PIPE, 
                               text=True)

    # Wait a bit for the initial output
    time.sleep(1)

    # Send inputs to the program
    for input in inputs:
        process.stdin.write(input + '\n')
        process.stdin.flush()
        time.sleep(.2)  # Adjust as needed

    # Close stdin, read output, and wait for the process to exit
    process.stdin.close()
    output = process.stdout.read()
    process.wait()

    return output

if __name__ == "__main__":
    inputs = sys.argv[1:]  # Get inputs passed as command-line arguments
    print(interact_with_index(inputs))
